name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result libfl-dev
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: ros_example_pkg
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
                "skip-license-check": true
              }
            }
          fail_ci_if_error: false
          
      - uses: codecov/codecov-action@v3
        with:
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
         


